### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by eshanized** [Snigdha-OS/snigdhaos-blackbox#22]
### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://snigdha-os.github.io/documentation/introduction/contributing).

### Prerequisites

- [X] I'm using the latest version of the package. Read [How to see package version in Snigdha OS?](https://snigdhaos.org/blog/check-package-version-on-snigdha-os/)
- [X] I have cleared the package cache and reinstalled the package. Read [How to clear package cache?](https://snigdhaos.org/blog/check-package-version-on-snigdha-os/)
- [X] I have checked for latest package update.
- [X] I have tried the `sudo pacman -Syyu` or `update` command.
- [X] I have read the console error message carefully (if applicable).
- [X] I am not using virtual machine.

### Package Name

snigdhaos-blackbox

### Description

```bash
CMake Error at CMakeLists.txt:52 (target_link_libraries):
  Target "SnigdhaOSBlackbox" links to:

    Qt6::Network

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
   ```

### Steps to reproduce

step 1: makepkg -f -scr --noconfirm

### Expected behavior

No error

### Actual behavior

cmake error

### Your PC Specification

- CPU: [e.g i5 1335U]
- RAM: [e.g 2 GiB]
- STORAGE: [e.g SSD/HDD]
- Snigdha OS Build: [e.g arctic]
- Snigdha OS Version: [e.g 4.5]

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by iconized** [comment]
Halka mute shuye poro @eshanized
